# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ci

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # 设置 Maven Settings
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: >
            [
              {
                "id": "ossrh-releases",
                "name": "ossrh releases",
                "url": "https://s01.oss.sonatype.org/content/repositories/releases/",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "ossrh-snapshots",
                "name": "ossrh snapshots",
                "url": "https://s01.oss.sonatype.org/content/repositories/snapshots/",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
      - name: Build with Maven
        run: mvn clean -B package -Pci --file pom.xml
      - name: Codecov
        uses: codecov/codecov-action@v1.2.2



